version: '3.8'

services:
  notification-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: mock