spring:
  application:
    name: gaming_challenge
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:mock}
  flyway:
    enabled: true
    baseline-on-migrate: true

---

logging:
  level:
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG